task:
  name: macOS
  osx_instance:
    image: high-sierra-xcode-10.0
  test_script: swift test

task:
  name: Linux
  container:
    image: swift
  test_script: swift test

task:
  name: CocoaPods Deploy
  depends_on:
    - macOS
    - Linux
  only_if: $CIRRUS_TAG =~ '\d+\.\d+\.\d+'
  osx_instance:
    image: high-sierra-xcode-10.0
  environment:
    COCOAPODS_PASSWORD: ENCRYPTED[9384d3346dae1690d5da71a1041d6a8a61b3c7b5465becb56626558e6b6705932b0dc8b4254be20073ec5c3801a640c5]
  pod_version_script: pod --version
  netrc_line1_script: echo "machine trunk.cocoapods.org" >> ~/.netrc
  netrc_line2_script: echo "  login hey.zooi@gmail.com" >> ~/.netrc
  netrc_line3_script: echo "  password $COCOAPODS_PASSWORD" >> ~/.netrc
  chmod_netrc_script: chmod 600 ~/.netrc
  pod_trunk_push_script: pod trunk push
